config/routes.rb
IkonBlvd::Application.routes.draw do
  #landing page routes
  match "beta_signup" =>  "home#beta_signup"
  match "health_check" => "home#health_check"
  
  match "silverline" => "home#login"
  match "index" => "home#index"
  match "landing" => "home#landing"
  
  #devise
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => "home#login"

  #tagged quotes routes
  match '/t/:tag_name/' => 'tagged_quotes#index',             :as => :tagged_quotes
  match 't/:tag_name/q/:quote_id' => 'tagged_quotes#show',    :as => :tagged_quote
  match 't/:tag_name/q/next' => 'tagged_quotes#next',         :as => :next_tagged_quote
  match 't/:tag_name/q/previous' => 'tagged_quotes#previous', :as => :previous_tagged_quote
  
  devise_for :users

  resources :user_profiles
  resources :authentications
  resources :user_dreams, :only => :create

  match 'quotes/:id' => redirect('/q/%{id}') #legacy redirect
  resources :quotes, :only => [:create, :show], :path => "q" do
    member do
      get 'previous'
      get 'next'
    end
  end
  resources :authors, :except => [:destroy]

  resources :user_assets, :only => :new do
    collection do
      post 'upload'
    end
  end
  
  root :to => 'home#index'
end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author

  validates :description, :author_id, :tag_list, :presence => true

  acts_as_taggable

  scope :previous, lambda { |p| {:conditions => ["id < ?", p.id], :limit => 1, :order => "id DESC"} }
  scope :next, lambda { |p| {:conditions => ["id > ?", p.id], :limit => 1, :order => "id"} }
  scope :by_date, order("created_at DESC")
  
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  def create
    q = Quote.new(params[:quote])
    q.user_profile_id = current_user.user_profile.id
    q.save

    redirect_to user_profile_path(current_user.user_profile)
  end
  
  def show
    @quote = Quote.find(params[:id])
  end

  def previous
    current_quote = Quote.find(params[:id])
    prev_quote = Quote.previous(current_quote).first

    #app has reached the first quote and no more previous quotes exist, so display the last one
    if prev_quote.nil?
      prev_quote = Quote.last
    end
    redirect_to quote_path(prev_quote)
  end

  def next
    current_quote = Quote.find(params[:id])
    next_quote = Quote.next(current_quote).first

    #app has reached the last quote and no more next quotes exist, so display the first qutoe
    if next_quote.nil?
      next_quote = Quote.first
    end
    redirect_to quote_path(next_quote)
  end
end

app/views/quotes/show.html.erb
<% content_for :og_metatags do %>
	<!--Facebook OG Meta Tags-->
	<meta property="fb:app_id" 		content="490964707588512" /> 
	<meta property="og:type"   		content="website" />
    <meta property="og:url"    		content="http://www.viadreams.com/q/<%= @quote.id %>" />
    <meta property="og:title"  		content="<%= @quote.description %>" />
    <meta property="og:description" content="@<%= @quote.author.name %>" />
    <meta property="og:image"  		content="<%= @quote.author.thumbnail(:thumb) %>" />
	<meta property="og:site_name" 	content="viadreams.com" />
	<meta property="fb:admins" 		content="15100760" />
<% end %>

<div id="quote_wrapper">
  <div id="quote_tags">
    <% @quote.tag_list.each do |tag| %>
        <p> #<%= tag %> </p>
    <% end %>
  </div>

  <div class="transparentBox">
    <!--previous quote button-->
    <div id="quote_container_left">
      <a href="<%=previous_quote_path(@quote.id)%>" class="previousIcon"></a>
    </div>

    <!--next quote button-->
    <div id="quote_container_right">
      <a href="<%=next_quote_path(@quote.id)%>" class="nextIcon"></a>
    </div>

    <!--actual quote-->
    <div id="quote_container_top">
      <blockquote><%= @quote.description %></blockquote>
    </div>

    <!--author name and social share-->
    <div id="quote_container_bottom">
	  <div id="social_share">
		<fb:like send="false" href="http://www.viadreams.com/quotes/<%= @quote.id %>" layout="button_count" width="450" show_faces="false" colorscheme="light"></fb:like>
	  </div>
      <div id="author_name">
        <h1> @<%= @quote.author.name %> </h1>
      </div>
      <div id="author_pic_thumb_container">
        <a href="#">
          <div id="author_pic_thumb">
            <%= image_tag @quote.author.thumbnail(:thumb) %>
          </div>
        </a>
      </div>
    </div>
  </div>
</div>