config/routes.rb
IkonBlvd::Application.routes.draw do
  #landing page routes
  match "beta_signup" =>  "home#beta_signup"
  match "health_check" => "home#health_check"
  
  match "silverline" => "home#login"
  match "index" => "home#index"
  match "landing" => "home#landing"
  
  #devise
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => "home#login"

  #tagged quotes routes
  match '/t/:tag_name/' => 'tagged_quotes#index',             :as => :tagged_quotes
  match 't/:tag_name/q/:quote_id' => 'tagged_quotes#show',    :as => :tagged_quote
  match 't/:tag_name/q/next' => 'tagged_quotes#next',         :as => :next_tagged_quote
  match 't/:tag_name/q/previous' => 'tagged_quotes#previous', :as => :previous_tagged_quote
  
  devise_for :users

  resources :user_profiles
  resources :authentications
  resources :user_dreams, :only => :create

  match 'quotes/:id' => redirect('/q/%{id}') #legacy redirect
  resources :quotes, :only => [:create, :show], :path => "q" do
    member do
      get 'previous'
      get 'next'
    end
  end
  resources :authors, :except => [:destroy]

  resources :user_assets, :only => :new do
    collection do
      post 'upload'
    end
  end
  
  root :to => 'home#index'
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :quotes

  has_attached_file :thumbnail,
                    :styles => {
                        :thumb => "200x200#"
                    },
                    :storage => :s3,
                    :s3_credentials => {
                        :bucket            => ENV['S3_BUCKET_NAME'],
                        :access_key_id     => ENV['AWS_ACCESS_KEY_ID'],
                        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    :path => "authors/:style/:filename",
                    :default_url => 'http://www.viadreams.com/assets/made_it_silhouette_bw.png'
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.order('lower(name)').all
  end

  def create
    author = Author.new(params[:author])
    author.save

    redirect_to new_author_path
  end

  def update
    author = Author.find(params[:id])
    author.update_attributes(params[:author])
    redirect_to edit_author_path(author)
  end

  def edit
    @author = Author.find(params[:id])
  end

end

app/views/authors/edit.html.erb
<div class="form_well">
  <h2>Add a new author</h2>
  <%= form_for @author, :url => author_path(@author), :html => {:multipart => true} do |f| %>
      <h3>ID: <%= @author.id %></h3>
      <%= f.text_field :name, :placeholder => "Author name", :class => "span5" %>
      <%= f.text_field :slug, :placeholder => "Author slug", :class => "span5" %>
      <%= image_tag(@author.thumbnail(:thumb)) %>
      <%= f.file_field :thumbnail, :class => "span5" %>
      <%= f.submit :class => "btn btn-info", :value => "Update It" %>
  <% end %>
</div>

app/views/authors/index.html.erb
<div class="form_well">
  <% @authors.each do |a| %>
      <ul>
        <li><%= link_to(a.name, edit_author_path(a)) %></li>
      </ul>
  <% end %>
</div>

app/views/authors/new.html.erb
<div class="form_well">
  <h2>Add a new author</h2>
  <%= form_for :author, :url => authors_path, :html => {:multipart => true} do |f| %>
      <%= f.text_field :name, :placeholder => "Author name", :class => "span5" %>
      <%= f.text_field :slug, :placeholder => "Author slug", :class => "span5" %>
      <%= f.file_field :thumbnail, :class => "span5" %>
      <%= f.submit :class => "btn btn-info", :value => "Create It" %>
  <% end %>
</div>