config/routes.rb
IkonBlvd::Application.routes.draw do
  #landing page routes
  match "beta_signup" =>  "home#beta_signup"
  match "health_check" => "home#health_check"
  
  match "silverline" => "home#login"
  match "index" => "home#index"
  match "landing" => "home#landing"
  
  #devise
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => "home#login"

  #tagged quotes routes
  match '/t/:tag_name/' => 'tagged_quotes#index',             :as => :tagged_quotes
  match 't/:tag_name/q/:quote_id' => 'tagged_quotes#show',    :as => :tagged_quote
  match 't/:tag_name/q/next' => 'tagged_quotes#next',         :as => :next_tagged_quote
  match 't/:tag_name/q/previous' => 'tagged_quotes#previous', :as => :previous_tagged_quote
  
  devise_for :users

  resources :user_profiles
  resources :authentications
  resources :user_dreams, :only => :create

  match 'quotes/:id' => redirect('/q/%{id}') #legacy redirect
  resources :quotes, :only => [:create, :show], :path => "q" do
    member do
      get 'previous'
      get 'next'
    end
  end
  resources :authors, :except => [:destroy]

  resources :user_assets, :only => :new do
    collection do
      post 'upload'
    end
  end
  
  root :to => 'home#index'
end

app/models/authentication.rb
class Authentication < ActiveRecord::Base
  belongs_to  :user

end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :quotes

  has_attached_file :thumbnail,
                    :styles => {
                        :thumb => "200x200#"
                    },
                    :storage => :s3,
                    :s3_credentials => {
                        :bucket            => ENV['S3_BUCKET_NAME'],
                        :access_key_id     => ENV['AWS_ACCESS_KEY_ID'],
                        :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                    },
                    :path => "authors/:style/:filename",
                    :default_url => 'http://www.viadreams.com/assets/made_it_silhouette_bw.png'
end

app/models/beta_signup.rb
class BetaSignup < ActiveRecord::Base
  validates   :email, :presence => true, :email => true

end

app/models/quote.rb
class Quote < ActiveRecord::Base
  belongs_to :author

  validates :description, :author_id, :tag_list, :presence => true

  acts_as_taggable

  scope :previous, lambda { |p| {:conditions => ["id < ?", p.id], :limit => 1, :order => "id DESC"} }
  scope :next, lambda { |p| {:conditions => ["id > ?", p.id], :limit => 1, :order => "id"} }
  scope :by_date, order("created_at DESC")
  
end

app/models/tag.rb
class Tag < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many  :authentications
  has_one   :user_profile

  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me



  def apply_omniauth(omniauth)
    self.email = omniauth['info']['email'] if email.blank?
    authentications.build(:provider => omniauth['provider'], :uid => omniauth['uid'])
  end

  def create_profile(omniauth)
    #persist user's facebook data that was retrieved via omniauth
    fb_user_info = omniauth["info"]
    self.user_profile = UserProfile.new(:image_path => fb_user_info["image"], :first_name => fb_user_info["first_name"], :last_name => fb_user_info["last_name"])
  end

  def password_required?
    (authentications.empty? || !password.blank?) && super
  end

end

app/models/user_asset.rb
class UserAsset < ActiveRecord::Base
  
  belongs_to  :user_profile
  
  has_attached_file :image,
      :styles => {
          :pinterest_lg => "600>",
          :pinterest => "192>",
      }
  
  validates_attachment :image, :presence => true,                  
end

app/models/user_dream.rb
class UserDream < ActiveRecord::Base
  validates  :dream, :presence => true

  belongs_to  :user_profile
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  
  attr_accessible :image_path, :first_name, :last_name, :zipcode

  belongs_to  :user
  has_many    :user_assets
  has_many    :user_dreams

  def full_name
    "#{first_name} #{last_name}"
  end

  def image_path
    self[:image_path].gsub("type=square","type=large")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  def index
    @authors = Author.order('lower(name)').all
  end

  def create
    author = Author.new(params[:author])
    author.save

    redirect_to new_author_path
  end

  def update
    author = Author.find(params[:id])
    author.update_attributes(params[:author])
    redirect_to edit_author_path(author)
  end

  def edit
    @author = Author.find(params[:id])
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    redirect_to index_path if current_user
  end
  
  def index
    # @user_assets = UserAsset.find(:all)
    # @user_dreams = UserDream.find(:all)
    @quotes = Quote.by_date.all
    @tags = Tag.order("name ASC").all

  end
  
  def health_check
    render :text => 'pass'
  end
  
  
  #### Landing page related calls ####
  def landing
    #when removing landing page, remove both home/landing.html.erb and layout/landing.html.erb
    render :layout => 'landing'
  end
  
  def beta_signup
    email = params['beta_signup_input']
    bs = BetaSignup.new(:email => email)
    if (bs.save)
      render :nothing => true
    else
      render :json => 'Email Signup Failed.', :status => 500
    end
  end
  
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  
  def create
    q = Quote.new(params[:quote])
    q.user_profile_id = current_user.user_profile.id
    q.save

    redirect_to user_profile_path(current_user.user_profile)
  end
  
  def show
    @quote = Quote.find(params[:id])
  end

  def previous
    current_quote = Quote.find(params[:id])
    prev_quote = Quote.previous(current_quote).first

    #app has reached the first quote and no more previous quotes exist, so display the last one
    if prev_quote.nil?
      prev_quote = Quote.last
    end
    redirect_to quote_path(prev_quote)
  end

  def next
    current_quote = Quote.find(params[:id])
    next_quote = Quote.next(current_quote).first

    #app has reached the last quote and no more next quotes exist, so display the first qutoe
    if next_quote.nil?
      next_quote = Quote.first
    end
    redirect_to quote_path(next_quote)
  end
end

app/controllers/tagged_quotes_controller.rb
class TaggedQuotesController < ApplicationController

  #filter index page quotes with selected tag
  def index
    @quotes = Quote.tagged_with(params[:tag_name]).by_date
    @tags = Tag.order("name ASC").all

    render "home/index"
  end


  def show

  end

  def next

  end

  def previous

  end


end

app/controllers/user_assets_controller.rb
class UserAssetsController < ApplicationController
  
  def upload
    asset = UserAsset.new(params[:asset])
    asset.user_profile_id = current_user.user_profile.id
    asset.save
    
    redirect_to user_profile_path(current_user.user_profile)
    
  end
  
end

app/controllers/user_dreams_controller.rb
class UserDreamsController < ApplicationController

  def create
    ud = UserDream.new(params['user_dream'])
    ud.user_profile_id = current_user.user_profile.id
    ud.save

    redirect_to user_profile_path(current_user.user_profile)
  end

end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  def show
    @user_assets = current_user.user_profile.user_assets
    @user_dreams = current_user.user_profile.user_dreams
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def escape_single_quote (str)
    str.gsub(/\\|'/) { |c| "\\#{c}" }
  end
  
end

app/helpers/authentications_helper.rb
module AuthenticationsHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/layouts/_ga.html.erb
<script type="text/javascript">

    var _gaq = _gaq || [];
    _gaq.push(['_setAccount', 'UA-35561177-1']);
    _gaq.push(['_trackPageview']);

    (function() {
        var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
        ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
        var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
    })();

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en"
      xmlns:og="http://ogp.me/ns#"
      xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
  <title>viadreams</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= yield :og_metatags%>

  <!--GA Tracking code-->
  <%= render :partial => 'layouts/ga' %>
</head>

<script>
	$(function(){
		<%= yield :ready %>
	});
</script>

<body>
	<div id="fb-root"></div>
	<div id="container">
		<div class="navbar navbar-fixed-top">
		    <div class="navbar-inner">
		      <div class="container">
                <div class="brand">
		            <a href="/index"> <%= image_tag "viadreams_stamp_logo.png" %></a>
                </div>
		        <div class="container nav-collapse">
		          	<ul class="nav pull-right">
						<% if user_signed_in? %>
							<li><%= link_to current_user.user_profile.first_name + "#{ }" + current_user.user_profile.last_name, user_profile_path(current_user.user_profile) %></li>
							<li><%= link_to "Sign out", destroy_user_session_path %></li>
						<% end %>
					</ul>
		        </div>
		        <!--/.nav-collapse -->
		      </div>
		    </div>
		  </div>
	
	    <div id="content">
			<%= yield %>
		</div>
	</div>

</body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>IkonBlvd</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body class="landing">
	<%= yield %>
</body>
</html>

app/views/shared/_create_asset_form.html.erb
<div class="input-append">
<%= form_for :asset, :url => upload_user_assets_path, :html => {:multipart => true} do |f| %>

    <%= f.file_field :image, :class => "span5" %>
    <%= f.submit :class => "btn btn-info", :value => "Upload It" %>
<% end %>
</div>

app/views/shared/_create_dream_form.erb
<div class="input-append">
<%= form_for :user_dream, :url => user_dreams_path do |f| %>
    <%= f.text_field :dream, :placeholder => "Share your thought", :class => "span5" %>
    <%= f.submit :class => "btn btn-info", :value => "Share It " %>
<% end %>
</div>

app/views/shared/_create_quote_form.erb
<%= form_for :quote, :url => quotes_path do |f| %>
    <%= f.text_area :description, :placeholder => "Share a quote", :class => "span5", :size => "5x5" %>
	<%= select("quote", "author_id", Author.order('lower(name)').all.collect {|a| [ a.name, a.id ] }, {:prompt => 'Select Author'}) %>
    <%= link_to "Add Author", new_author_path %>
	<%= f.text_field :tag_list, :placeholder => "Add tags (comma separated)", :class => "span5" %>
	</br></br>
	<%= f.submit :class => "btn btn-info btn-large", :value => "Share It " %>
<% end %>

app/views/shared/_taglist.html.erb
<div id="taglist" class="transparentBox shadow">
    <% tags.each do |t| %>
        <%= content_tag(:ul) do %>
        	<%= content_tag(:li, :class => "tag#{[1,2,3,4].sample}") do %>
            	<%= link_to "##{t.name}", tagged_quotes_path(t.name.downcase) %>
            <% end %>
        <% end %>
    <% end %>
</div>