config/routes.rb
IkonBlvd::Application.routes.draw do
  #landing page routes
  match "beta_signup" =>  "home#beta_signup"
  match "health_check" => "home#health_check"
  
  match "silverline" => "home#login"
  match "index" => "home#index"
  match "landing" => "home#landing"
  
  #devise
  match '/auth/:provider/callback' => 'authentications#create'
  match '/auth/failure' => "home#login"

  #tagged quotes routes
  match '/t/:tag_name/' => 'tagged_quotes#index',             :as => :tagged_quotes
  match 't/:tag_name/q/:quote_id' => 'tagged_quotes#show',    :as => :tagged_quote
  match 't/:tag_name/q/next' => 'tagged_quotes#next',         :as => :next_tagged_quote
  match 't/:tag_name/q/previous' => 'tagged_quotes#previous', :as => :previous_tagged_quote
  
  devise_for :users

  resources :user_profiles
  resources :authentications
  resources :user_dreams, :only => :create

  match 'quotes/:id' => redirect('/q/%{id}') #legacy redirect
  resources :quotes, :only => [:create, :show], :path => "q" do
    member do
      get 'previous'
      get 'next'
    end
  end
  resources :authors, :except => [:destroy]

  resources :user_assets, :only => :new do
    collection do
      post 'upload'
    end
  end
  
  root :to => 'home#index'
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def login
    redirect_to index_path if current_user
  end
  
  def index
    # @user_assets = UserAsset.find(:all)
    # @user_dreams = UserDream.find(:all)
    @quotes = Quote.by_date.all
    @tags = Tag.order("name ASC").all

  end
  
  def health_check
    render :text => 'pass'
  end
  
  
  #### Landing page related calls ####
  def landing
    #when removing landing page, remove both home/landing.html.erb and layout/landing.html.erb
    render :layout => 'landing'
  end
  
  def beta_signup
    email = params['beta_signup_input']
    bs = BetaSignup.new(:email => email)
    if (bs.save)
      render :nothing => true
    else
      render :json => 'Email Signup Failed.', :status => 500
    end
  end
  
end

app/views/home/index.html.erb
<% content_for :ready do %>
	var $userAssetsContainer = $('#user_assets_container');
	$userAssetsContainer.imagesLoaded(function(){
		$userAssetsContainer.masonry({
			itemSelector: '.assetBox',
			isAnimated: true,
			isFitWidth: true,
			columnWidth: 0,
		});
	});
<% end %>

<%= render :partial => 'shared/taglist', :locals => {:tags => @tags} %>
<div id="qutoes_index_container">
	<!-- <div id="featured_quote">
		<div class="transparentBox shadow">
			<blockquote>Life is short. Do what you love...</blockquote>
			<blockquote></blockquote>
		</div>
	</div> -->

	<!--quotes container-->
	<div id="user_assets_container">
		<% @quotes.each do |quote|%>
			<div class="assetBox shadow">
				<a href="<%= quote_path(quote) %>">
					<div class="assetBoxTopDiv">
						<blockquote><%= quote.description %></blockquote>
					</div>
				</a>
				<div class="assetBoxBottomDiv">
					<p>@<%= quote.author.name unless quote.author.nil? %></p>
				</div>
			</div>
		<% end %>
	</div>
</div>

app/views/home/landing.html.erb
<script>

	$(document).ready(function() {
		//clear email input
		$("#beta_signup_input").click(function() {
			$(this).val("");
		})
		
		//Display Beta Signup success/error message
		$("#beta_signup_form")
			.bind("ajax:success", function(e, data, status, xhr){
				$("#beta_signup_input").css("border", "none");
				$("#notification p").text("Thank You for your interest!").css("color", "green");
			})
			.bind("ajax:error", function(e, xhr, status, error){
				$("#beta_signup_input").css("border", "solid");
				$("#beta_signup_input").css("border-width", "1px");
				$("#beta_signup_input").css("border-color", "rgba(255, 0, 0, .5)");
				$("#notification p").text("Oops! Seems like the email is incorrect.").css("color", "rgba(255, 0, 0, .75)");
			});
		
	});

</script>
<div class="wrap">
	<div id="landing_content">
		<div id="logo">
			<a class="transform" href="#"> </a>
			<p>Coming Soon...</p>
		</div> <!--END logo-->
		<div class="headline">
			<p>Life is an art. Paint your dreams.</p>
		</div>
		<div class="sub_headline">
			<p>Share. Discover. Collaborate. Build.</p>
		</div>
		<div id="beta_signup">
			<form id="beta_signup_form" method="post" action="/beta_signup" data-remote="true">
				<div class="left">
					<input id="beta_signup_input" name="beta_signup_input" type="text" value="Enter your email to join the beta!">
				</div>
				<div class="right submit">	
					<input class="submit_button" type="submit" value="Go"/>
				</div>
			</form>
		</div> <!--END beta_signup-->
		<div id="notification">
			<p></p>
		</div>
	</div> <!--END Content-->
</div> <!--END wrap-->

app/views/home/login.html.erb
<div id="login_container">
	<a href="/auth/facebook" class="auth_provider">
    <%= image_tag "/assets/fb_login_button.png", :alt => "Facebook" %>
  </a>
</div>